### ISSUE TITLE
是否可以考虑加入复制和插入复制行功能？

### ISSUE THREAD

**Issue by cloudherder** [Stardusten/ob-table-enhancer#11]
这个插件太赞了，现在已经拿来做主力表格。但每次填表，有些内容是重复的，每次都要填很烦，可不可以增加复制行和插入复制行的按钮呢？
谢谢！

**Comment by Stardusten** [comment]
最新版本 [0.3.2-alpha](https://github.com/Stardusten/ob-table-enhancer/releases/tag/0.3.2-alpha) 已经加入克隆行 / 列的功能，欢迎试用。

这个版本还不稳定，生产环境下要**慎用**！
