### ISSUE TITLE
有时候点击有内容的格子内容会消失，

### ISSUE THREAD

**Issue by Russra-tuiop** [Stardusten/ob-table-enhancer#12]
使用中发现的一些问题：有时候点击有内容的格子内容会消失，消失的内容在源码模式下是不受影响的，重新点回阅览模式又会重新出现或者先切到别的页面再切回来也能恢复显示；并且在这种情况下即使重新编辑或者另起新行输入内容后也是无用功（变回空白且源码模式种内容没有新增或者减少）。
另外偶尔点击增加列或者行的图标会没有反应，这是什么缘故？我关闭其他和table相关的插件尝试也会有这样的bug
总体来讲真的很好用我还是蛮需求这个插件，但是这些问题想解决。

**Comment by Stardusten** [comment]
这是表格索引的问题，对某些特殊的表格（比如含有特殊字符、HTML 元素）现在的索引方法可能有问题，不是太好解决。可以麻烦发一下有问题的表格吗？

**Comment by Russra-tuiop** [comment]
知道问题出在哪里了，确实是格式问题，因为我是从别的地方迁移过来的文字数据，一些是直接从表格复制，所以时不时出现这个问题，后来旧的迁移完我自己输入新文字填表，这两天都没再出现这个问题了。（这个辅助插件真好用O(∩_∩)O）
