### ISSUE TITLE
预览填好表格，但代码里没有内容

### ISSUE THREAD

**Issue by Alex-coder251** [Stardusten/ob-table-enhancer#16]
![image](https://user-images.githubusercontent.com/58896036/195328724-a4072545-6280-46bd-88a7-d69f5d717a37.png)
![image](https://user-images.githubusercontent.com/58896036/195328788-7d25e23b-0f3c-48c9-9d59-ade9f73aabd7.png)
如图，为什么会这样啊，求开发者大大解答😭

**Comment by Stardusten** [comment]
麻烦给一个复现步骤：包括系统、ob 版本，编辑时所处的模型，操作方法（输了什么东西，怎么建立的表格）等。

**Comment by Alex-coder251** [comment]
obsidian: v0.15.9（安装程序版本：v0.15.8）
editing toolbar: v2.1.7
table generator: v1.3.1
table enhancer: v0.2.2
我通过editing toolbar用table enhancer生成了空白表格，然后直接随便填的

下面是我用的md文件

> ```notion-like-tables
>table-id-h6yAtw
>```
>
>|      |      |      |
>|:-----|:-----|:-----|
>|      |      |      |
>|      |      |      |
>

**Comment by Alex-coder251** [comment]
> 麻烦给一个复现步骤：包括系统、ob 版本，编辑时所处的模型，操作方法（输了什么东西，怎么建立的表格）等。

我又试了一下。发现只要前面带有notion-like tables的样式，后面table enhancer表格就无法正常输入
>```notion-like-tables
>table-id-h6yAtw
>```

**Comment by viperbbb** [comment]
1.0 适用版本呢，现在用不了。。

**Comment by chenxin0397** [comment]
还会升级吗？

**Comment by Stardusten** [comment]
> 1.0 适用版本呢，现在用不了。。

麻烦新开一个 issue，并且说明问题和具体复现步骤。我目前 1.0 使用是没有问题的。

**Comment by Stardusten** [comment]
> 还会升级吗？

大多数 bug 还是来自 obsidian 提供的 api 不足（比如长表格乱跳），这个插件实现思路本身的限制（比如空表格无法编辑、含有极少数特殊内容的表格会失效）以及其他插件的干扰（比如 notion-like tables，admonition）。如果之后有功能上的大问题，肯定会跟进修复，但现在没什么修改的动力。
