### ISSUE TITLE
插件生成的表格，无法正常共工作

### ISSUE THREAD

**Issue by juestchaos** [Stardusten/ob-table-enhancer#17]
我通过editing toolbar用table enhancer生成了空白表格

但是鼠标指向表格后，无法显示表格行列编辑工具条
点击单元格也无法，进入单元格进行编辑

我尝试把配置和插件都放入一个新的库，是正常运行。
查看页面后
发现鼠标在表格上指向时
 ‘ob-table-enhancer-col-bar’ ‘ob-table-enhancer-row-bar’
对应的 style 没有获得 对应 position，opacity 也没有从0 变到1

windows 10
obsidian: v1.0.0
editing toolbar: v2.1.7
table generator: v1.3.1
table enhancer: v0.2.2

**Comment by Stardusten** [comment]
因为这个插件需要根据表格的特征（行数、列数、单元格内的文字等）找到你正在编辑的表格对应的源码。而一个空白表格很可能缺少足够的用于定位的特征，导致无法编辑。

总之就是，尽量避免创建空白表格，不要和其他同类插件一起使用。这个插件提供了一个创建 2x2 表格的 command，这个指令创建表格表头默认是 col1，col2 这种，能被正确索引。

**Comment by juestchaos** [comment]
我尝试了很多方式，发现确实对表格 在源码下的格式（尤其是空表状态下）要求很高
而且我发现在 窗口模式下，这个插件的浮动工具是完全不生效的。
