### ISSUE TITLE
[Problem] 畫面晃動現象

### ISSUE THREAD

**Issue by emisjerry** [Stardusten/ob-table-enhancer#18]
搜尋時，找到的最開頭有井號(標題行)時，視窗畫面會晃動。

下方影片是在Quiet Outline plugin點擊標題時，Obsidian window會有震動現象。
原本以為是Quiet Outline的問題，逐一排查後確認只要開啟Table Enhancer才會出現此狀況。
後來發現用Ctrl+F搜尋也有此狀況。

請檢視執行錄影(Default 佈景主題)：
https://youtu.be/gky2pO_j-8c

使用環境: 
- Windows 11
- Obsidian 1.0.3
- Table Enhancer 使用BRAT安裝

**Comment by emisjerry** [comment]
剛剛測試：當勾選 Floating toolbar時才會發生晃動狀況。

**Comment by Stardusten** [comment]
能不能发一下出现问题的 md 源码呢？我复现不了这个问题。

**Comment by emisjerry** [comment]
使用沙盒儲存庫(sandbox vault):

1. 先安裝BRAT外掛，再安裝Table enhancer，啟用Floating toolbar
2. 開啟 Start Here.md
3. 按Ctrl+F, 搜尋 office
4. 按Next時出現晃動現象
5. 點擊大綱面板的Office也會晃動

操作影片：https://youtu.be/T1u_oISmSS8
影片後面有關閉與開啟Floating toolbar後的測試狀況

**Comment by Stardusten** [comment]
这个问题应该是悬浮菜单导致的。最新版 [0.4.0](https://github.com/Stardusten/ob-table-enhancer/releases/tag/0.4.0) 可以关闭悬浮菜单，并提供了右键按钮面板用于代替悬浮菜单。

**Comment by emisjerry** [comment]
不行。重新安裝使用，關閉floating panel，按 Ctrl+F 搜尋，輸入到第三個字就開始晃動了。
