### ISSUE TITLE
[bug]点击页面自动上移

### ISSUE THREAD

**Issue by subframe7536** [Stardusten/ob-table-enhancer#2]
很棒的插件！其他的表格插件已经卸了！
只是有个bug比较影响体验
版本0.0.9
![image](https://user-images.githubusercontent.com/78338239/187391126-580ce268-3eaa-45be-8ecc-5c04ebf93d5f.png)
点击padding部分页面会自动上移
- 另外建议工具栏跟随页面移动，现在是固定的？

**Comment by subframe7536** [comment]
> * 点击 padding 页面自动上移
>   这个我复现不了，而且不太清楚描述的意思。正常的话，点击单元格的会进入编辑模式，您遇到的问题是点 padding 部分无法进入编辑模式，然后页面网上滚动吗？

是的，后来我也试了一下，应该是在第一次加载后点击才会出现
[复现.webm](https://user-images.githubusercontent.com/78338239/187452218-9b8031ce-3fc1-4454-8c57-dd607eab054a.webm)

**Comment by Stardusten** [comment]
页面异常滚动问题在 0.0.11 中应该修好了，麻烦测试一下。

工具栏随页面移动对性能有一定影响，ob 的 tooltip 也是不随页面滚动的。在 0.0.11 里，我改成了滚动的时候不显示工具栏，停止滚动时再显示，感觉效果还能接受。

**Comment by subframe7536** [comment]
很不错，现在ob的表格终于不是短板了🤩
