### ISSUE TITLE
多个表格问题

### ISSUE THREAD

**Issue by 2913064141** [Stardusten/ob-table-enhancer#20]
当一个标签页存在多个表格时，在两个表格切换码字会偶尔出现焦点无法获取，部分表格内容转移（本来在表格2的一个表格单元转移到了表格1），表格单元获取焦点后原有内容消失；上述问题在表格含有行内代码块时出现的更频繁

**Comment by Stardusten** [comment]
请试用一下 [0.3.1-alpha](https://github.com/Stardusten/ob-table-enhancer/releases/tag/0.3.1-alpha)，注意不要使用工作库，防止数据丢失。
