### ISSUE TITLE
使用 Obsidian 1.0.3, plugin 安裝後無反應

### ISSUE THREAD

**Issue by edwardsayer** [Stardusten/ob-table-enhancer#21]
如題，使用 Obsidian 1.0.3, plugin 安裝後
將指標移至表格上，仍顯示表格原碼

用開發者工具檢視，table enhancer 應是有啟動，table id 是亂碼:
![圖片](https://user-images.githubusercontent.com/98105/205483368-26faf03c-7c9b-4248-b182-c65dd86daa00.png)

console沒有顯示任何錯誤訊息

**Comment by Stardusten** [comment]
这是正常的，目前表格 id 就一个字符，因此看上去就是乱码。使用上有什么问题吗？

**Comment by edwardsayer** [comment]
抱歉，比較晚看到回應。
但是，我安裝並啟用後，將指標移到表格上，
仍顯示 markdown 語法如下，並不會出現表格編輯器：
![圖片](https://user-images.githubusercontent.com/98105/205855106-34e026c0-4b6b-4888-96a8-0802f5fb34db.png)

**Comment by platon-ivanov** [comment]
该插件对我也不起作用。表格被渲染成没有安装该插件的样子。插入表格的命令是有效的。

**Comment by Stardusten** [comment]
> 该插件对我也不起作用。表格被渲染成没有安装该插件的样子。插入表格的命令是有效的。



> 抱歉，比較晚看到回應。 但是，我安裝並啟用後，將指標移到表格上， 仍顯示 markdown 語法如下，並不會出現表格編輯器： ![圖片](https://user-images.githubusercontent.com/98105/205855106-34e026c0-4b6b-4888-96a8-0802f5fb34db.png)

能看看控制台有什么报错吗，比如插件加载失败之类的？启用其他表格插件也有可能导致冲突。

另：使用 CodeMirror6 API 重写了一个测试版本，之前各种因为表格索引导致的问题应该都能解决，欢迎试用！

**Comment by platon-ivanov** [comment]
我在控制台中没有任何信息。

新的实施方案确实有效。谢谢你！"。我将期待着新的功能。

**Comment by edwardsayer** [comment]
同上， 控制台中没有任何信息。新版可正常使用了！謝謝！
