### ISSUE TITLE
canvas support

### ISSUE THREAD

**Issue by KuiyueRO** [Stardusten/ob-table-enhancer#22]
Can not edit table on the canvas,
`Enter` `Esc` `Tab` is unavailable

**Comment by Stardusten** [comment]
A lot of the api's used by this plugin don't work properly in canvas, so I can't solve this problem until official canvas api is released.

But I can add a feature to disable this plugin when it detects a canvas environment later, and you can continue to use other table plugins such as advanced table.

**Comment by KuiyueRO** [comment]
Thanks :)
