### ISSUE TITLE
能否添加列文本对齐方式

### ISSUE THREAD

**Issue by ku-zhen** [Stardusten/ob-table-enhancer#24]
能否添加列文本对齐方式，如列文本左对齐，中间对齐等功能？

**Comment by Stardusten** [comment]
右键菜单里有，感觉这个功能使用频率不高，因此没有放到浮动工具栏里

![image](https://user-images.githubusercontent.com/38722307/210576007-3822f6dd-86fb-4d46-8e59-c64093e5f538.png)
