### ISSUE TITLE
bug：启动后在设置面板的输入框后不能使用方向键

### ISSUE THREAD

**Issue by ku-zhen** [Stardusten/ob-table-enhancer#25]
如下视频：当在各个插件的设置面板输入框中使用右方向键->，会导致光标跳到当前面板最前面。其他方向键也无法使用。

https://user-images.githubusercontent.com/61906420/210474723-62114588-0aa0-4f7c-ac57-a5965541aa96.mp4

ob版本：1.1.9
插件版本：0.3.5

**Comment by Stardusten** [comment]
能够复现，下一个版本应该能修好。这个应该只有在有单元格处于编辑状态（没有按 esc / enter 退出编辑状态）时才会发生。

**Comment by Stardusten** [comment]
已经发了 0.3.6 版，应该已经修好了
