### ISSUE TITLE
造成文本搜索时的页面来回闪动

### ISSUE THREAD

**Issue by ghost** [Stardusten/ob-table-enhancer#26]
在1.1.9版本的ob下使用0.3.5版本的本插件时，在使用ctrl+F在笔记内搜索文本时（如“dataview”），当文本长度超过一定量时，会使得页面在打字时来回闪动

**Comment by Stardusten** [comment]
这个问题应该是悬浮菜单导致的。最新版 [0.4.0](https://github.com/Stardusten/ob-table-enhancer/releases/tag/0.4.0) 可以关闭悬浮菜单，并提供了右键按钮面板用于代替悬浮菜单。
