### ISSUE TITLE
Cells containing escaped pipe

### ISSUE THREAD

**Issue by zcysxy** [Stardusten/ob-table-enhancer#28]
When a cell contains an escaped pipe `\|`, the plugin will recognize it as the boundary of a cell.

For example,

```markdown
| A | B |
|:-:|:-:|
| [[note\|alias]] | C |
```

When I click the second cell, I want to edit the text `C`; however, the plugin shows `alias]] `, which is in the first cell.

**Comment by zcysxy** [comment]
A simple solution is to replace all instances of `.split("|")` with `.split(/(?<!\\)\|/)` in the code.

**Comment by Stardusten** [comment]
> A simple solution is to replace all instances of `.split("|")` with `.split(/(?<!\\)\|/)` in the code.

Thanks. This issue should be fixed in the latest release [0.3.8](https://github.com/Stardusten/ob-table-enhancer/releases/tag/0.3.8).
