### ISSUE TITLE
向表格内复制/黏贴文本异常

### ISSUE THREAD

**Issue by ku-zhen** [Stardusten/ob-table-enhancer#29]
黏贴内容后，实时预览模式能够看到数据，但在源码模式和阅读模式下，内容消失。直到下一次黏贴后，上一次黏贴的内容才出现。测试视频如下：

https://user-images.githubusercontent.com/61906420/212897739-bb762b27-3376-4b43-bbd6-6b8a961767aa.mp4

**Comment by Stardusten** [comment]
最新版 [0.5.1](https://github.com/Stardusten/ob-table-enhancer/releases/tag/0.5.1) 应该已经解决了这个问题

**Comment by ku-zhen** [comment]
抱歉，我测试问题还是存在，并且出现了一些新的bug。我将开一个新的issue来描述它
