### ISSUE TITLE
能不能加入一些图标呢？

### ISSUE THREAD

**Issue by chenxin0397** [Stardusten/ob-table-enhancer#3]
![image](https://user-images.githubusercontent.com/73974352/188257689-d87dd548-9812-4171-9d2e-dee8f342fd6e.png)

**Comment by Stardusten** [comment]
有悬浮工具栏，应该不需要这些图标了吧。

**Comment by chenxin0397** [comment]
这个插件好像和别的插件有冲突，不能双击点击单元格

**Comment by chenxin0397** [comment]
终于找到原因了，与
