### ISSUE TITLE
表格的实时预览与编辑功能失效、上下文菜单异常

### ISSUE THREAD

**Issue by ku-zhen** [Stardusten/ob-table-enhancer#30]
如视频：

https://user-images.githubusercontent.com/61906420/213379166-dae4eba8-85b0-4a95-b05b-5087cf77d48b.mp4

**Comment by ku-zhen** [comment]
插件：v0.5.1
ob：1.1.11

**Comment by Stardusten** [comment]
能开一个沙箱库测试一下吗？我这里没有问题（你这几乎是完全不能用了。。

**Comment by ku-zhen** [comment]
沙箱库除了实时预览问题不严重外，其他问题还是存在：
1. 复制黏贴会吞字符（经常性）
2. 表格外上下文菜单显示异常（偶发性）

测试视频如下：



https://user-images.githubusercontent.com/61906420/213401975-fa32146c-54da-4812-a430-27b6587013a8.mp4

**Comment by ku-zhen** [comment]
> 能开一个沙箱库测试一下吗？我这里没有问题（你这几乎是完全不能用了。。

在我的仓库中，我发现每次重启该插件，实时编辑能够正常工作，但是其他问题通用存在

**Comment by Stardusten** [comment]
你是在粘贴后马上从编辑模式切换到阅读模式了吗？这肯定不行的。现在的实现是正在编辑的单元格失焦，就把单元格的内容存起来。像点表格以外的其他地方，按 esc，enter 等操作都会触发这个事件。但是从编辑模式切到阅读模式不会，所以会导致单元格里写了东西，但阅读模式下看不到的情况。

你可以试试，不仅是复制粘贴，在单元格里随便输一些东西，然后切换到阅读模式，应该都不会显示出来。

**Comment by Stardusten** [comment]
但这个应该不会影响使用的，你输完以后按下 esc、enter 或者点一下其他地方，当前正在编辑的单元格里的内容就会被持久化到编辑器里面

**Comment by Stardusten** [comment]
> 表格外上下文菜单显示异常（偶发性）

这个问题确实存在。修起来可能有点麻烦，建议暂时继续用现在的 0.4.x

**Comment by Stardusten** [comment]
麻烦测试一下 [0.5.2](https://github.com/Stardusten/ob-table-enhancer/releases/tag/0.5.2) 是否还存在问题。

**Comment by ku-zhen** [comment]
非常感谢，沙箱应该没问题了。但我的仓库还是有问题，应该是插件导致的，我检测了下发现应该不是具体某个插件单独产生的，有可能是多个插件复合产生了莫名其妙的冲突。

感谢您的付出，等稳定版，我再试试，谢谢~
