### ISSUE TITLE
Alignment buttons not working

### ISSUE THREAD

**Issue by cs-mshah** [Stardusten/ob-table-enhancer#33]
The alignment buttons don't seem to work

[Screencast from 20-01-23 09:07:46 PM IST.webm](https://user-images.githubusercontent.com/56499208/213740899-585a759a-a8d6-4e0f-a108-d7c16eaad6ca.webm)

**Comment by Stardusten** [comment]
This should be fixed in the latest release [0.5.5](https://github.com/Stardusten/ob-table-enhancer/releases/tag/0.5.5).
