### ISSUE TITLE
Autocomplete Links

### ISSUE THREAD

**Issue by Signynt** [Stardusten/ob-table-enhancer#34]
When writing Links there is no autocomplete prompt, like in regular typing in Obsidian.
Additionally, using shortcuts inside the table to create bold text (Ctrl/Cmd + B), or links (Ctrl/Cmd + L) does not work.

**Comment by Stardusten** [comment]
Due to the implementation limitaion, you cannot use any other plugins as well as the official editor features (e.g. some hotkeys, link completions, etc.) when you are typing in a table cell.
