### ISSUE TITLE
安装后无法正常使用

### ISSUE THREAD

**Issue by inigeft** [Stardusten/ob-table-enhancer#37]
安装本插件后，无法使用，具体表现为：
1. 笔记中右击，选择Create new table后小弹窗显示空白，如下图（应显示行数列数配置界面）；
![image](https://user-images.githubusercontent.com/69950409/213900327-01a3c031-8977-4a06-9479-f17303ebb439.png)
2. Ctrl+P呼出命令菜单搜不到Table Enhancer相关命令

参考信息：
1. Obsidian版本为V1.1.9，插件版本V0.5.5、V0.5.4均无法工作（BRAT方式、手动安装方式均尝试过）
2. 为避免其他插件冲突，已提前关闭其他所有插件

**Comment by Stardusten** [comment]
请检查 Settings - Appearance - Native Menu 选项是否开启，如果开启，请关掉后再试试
