### ISSUE TITLE
Bug (or FR?): height control disrupted affecting minimal cards layout

### ISSUE THREAD

**Issue by efemkay** [Stardusten/ob-table-enhancer#38]
## Issue
- enabling the plugin, renders minimal cards layout (https://minimal.guide/Block+types/Cards) unusable due to table cell height being forced to be 1.5em only
- from my inspect, this css code seems to be culprit. appreciate if you can include an exclusion to dataview table (e.g. `:not(.dataview table-height-adjust th`)
```css
table-height-adjust th, .table-height-adjust tr {
    height: 1.5em !important;
}
```
> without the plugin
> ![image](https://user-images.githubusercontent.com/42369515/213900679-0ad471c8-78b1-4c62-afc0-6cdcaac668d0.png)

> with the plugin enabled
> ![image](https://user-images.githubusercontent.com/42369515/213900699-f9c2d6ad-6a8c-4e0a-8a59-42982007b46a.png)

## Current Workaround
- introduce a css snippet to override the change. however, since this is dataview, this plugin is not needed for it, so it is best to exclude the plugin css for dataview.

Thanks.

**Comment by Stardusten** [comment]
A simple workround would be to disable the "Adjust Height of Table Cells" option, and add custom css to control the related behaviors.

![image](https://user-images.githubusercontent.com/38722307/215004011-799cf0bb-d757-4db7-a5ef-441421cc7e4d.png)

**Comment by efemkay** [comment]
Owh. Just realised u introduced that CSS to handle empty cell. Perhaps using `min-height: 1.5em` instead?
