### ISSUE TITLE
Feature Request: Paste URL into selection

### ISSUE THREAD

**Issue by icebruce** [Stardusten/ob-table-enhancer#44]
It would be nice to add support for inserting links into a selected text. This is currently enabled by this Obsidian Plugin (https://github.com/denolehov/obsidian-url-into-selection)

Thanks for an awesome plugin!

**Comment by Stardusten** [comment]
Due to the implementation limitaion, you cannot use any other plugins as well as the official editor features (e.g. some hotkeys, link completions, etc.) when you are typing in a table cell.
