### ISSUE TITLE
Left arrow navigation not working

### ISSUE THREAD

**Issue by icebruce** [Stardusten/ob-table-enhancer#45]
Tab and all other arrow keys navigation work as expected.
However when using the `left` arrow key to move left between cells the cursor jumps to the top of the table instead

https://user-images.githubusercontent.com/66655064/215544077-6b2c45ac-3578-43ec-870f-1f19a9165325.mp4

**Comment by Stardusten** [comment]
I have also noticed this too, and I'll try to fix it in the next release.
