### ISSUE TITLE
Column width

### ISSUE THREAD

**Issue by Inclement9** [Stardusten/ob-table-enhancer#50]
It seems the default behavior is for the table to span the whole width of the tab, no matter what the contents are.
Example:

![image](https://user-images.githubusercontent.com/61940529/216323543-2ee9b95c-88d3-42ea-b64c-113a924c347a.png)

Also see how the second column is much wider than the first.

That doesn't seem like the best presentation. Is there a way to have it adjust to fit the contents, or even better, for users to adjust the width manually?

**Comment by Stardusten** [comment]
This plugin is not designed for styling table actually. Here are some solutions you may want to try :

1. If you use the minimal theme, it provides some table css snippets.
2. You can insert some unicode spaces to the header of column that are too narrow (`           `).

**Comment by Inclement9** [comment]
Will look into the snippets, thanks.
