### ISSUE TITLE
There's no prompting for blocks or sections (related to #34)

### ISSUE THREAD

**Issue by Inclement9** [Stardusten/ob-table-enhancer#51]
Related to issue #34.

Steps to reproduce:
1. Make a table.
2. Type `[[ ]]`
3. Type a filename between the `[[ ]]`, like `[[<filename>]]`
4. Go back inside the brackets and type `^` or `#` right after the filename: `[[<filename>#]]`

Expected behavior:
When you type `#` or `^`, there should be a popup listing all the available sections or blocks in `<filename>`.

**Comment by Stardusten** [comment]
Due to the implementation limitaion, you cannot use any other plugins as well as the official editor features (e.g. some hotkeys, link completions, etc.) when you are typing in a table cell.

**Comment by Stardusten** [comment]
Some frequently used features e.g. link completions and url paste maybe implement mannually in the future.
