### ISSUE TITLE
Image toolkit plugin bug

### ISSUE THREAD

**Issue by LostPaul** [Stardusten/ob-table-enhancer#56]
Currently, when you have the image toolkit plugin downloaded and enabled, the tooltips for the buttons in the menu get under it so that you can't see them.
<img src="https://user-images.githubusercontent.com/70213368/217937326-5753c6ab-c4ca-492d-910f-1bb501cf9c11.png" width="200" height="200">

That's a result of an CSS rule that changes the z index, so you can simply remove it, and it's fixed, from what I've looked at there's no difference without it.
![image](https://user-images.githubusercontent.com/70213368/217937204-49d9b497-a6b0-4ab0-8fc0-bcb99e5a18af.png)
^in the css file from image toolkit

Until the "bug" has been fixed in the image toolkit plugin, you should mention the issue somewhere in the README that other users get aware of it.

**Comment by Stardusten** [comment]
Fix it by set the tooltip's z-index higher than menu in the next release.
