### ISSUE TITLE
FR: Please Add Support for Reading Mode as well

### ISSUE THREAD

**Issue by chrisgrieser** [Stardusten/ob-table-enhancer#6]
Thanks for this wonderful implementation!

I was wondering whether you could add support for Reading Mode as well? Right now, it only seems to work in Live Preview (which, btw, could also be added to the README, I was a bit confused when it first didn't work for me in Reading Mode.)

**Comment by Stardusten** [comment]
It's really weird to edit tables in reading mode, and I don't think most people would need it.

However it's not too hard to implement, so I'll add it as an option to the settings panel in the next release, and users can choose whether to enabled this plugin in reading mode.

**Comment by chrisgrieser** [comment]
> It's really weird to edit tables in reading mode, and I don't think most people would need it.

well, there are people like me who do not use live preview, but only Reading mode and Source Mode. And in that case, it would be fantastic to edit the table in reading mode, so thank you! 🥳

**Comment by Stardusten** [comment]
Already implemented in release 0.2.2.

**Comment by chrisgrieser** [comment]
thanks! 🥳
