### ISSUE TITLE
Failed to load plugin ob-table-enhancer

### ISSUE THREAD

**Issue by Hamza-Anver** [Stardusten/ob-table-enhancer#63]
When trying to enable the plugin after downloading and extracting the file into the plugins folder, obsidian says that the file fails to load.

Same issue occurs in a vault with no other plugins or themes.

I'm probably messing up the installation for the plugin, any instructions to correct it would be appreciated

**Comment by LostPaul** [comment]
> When trying to enable the plugin after downloading and extracting the file into the plugins folder, obsidian says that the file fails to load.
> 
> Same issue occurs in a vault with no other plugins or themes.
> 
> I'm probably messing up the installation for the plugin, any instructions to correct it would be appreciated

You have to compile the source code or you can download the latest release from https://github.com/Stardusten/ob-table-enhancer/releases/tag/0.5.7

**Comment by Hamza-Anver** [comment]
Alrighty, I'll put in a PR with clearer download instructions in a bit. Hopefully this gets added to obsidians plugin library, cause it works really well
Thanks so much for your work!
