### ISSUE TITLE
Newest version makes calendar plugin disfunctional

### ISSUE THREAD

**Issue by tim-hilde** [Stardusten/ob-table-enhancer#68]
With the new update I cannot open a daily note from the calendar view as it throws the following error:
<img width="357" alt="image" src="https://user-images.githubusercontent.com/44113468/219001544-1170a093-f985-4cc8-a090-bf3e5b2e0e68.png">

I try to click on a date in this view:
<img width="265" alt="image" src="https://user-images.githubusercontent.com/44113468/219001690-1d218658-2a8e-44cc-8fe4-ecbab0e467da.png">

**Comment by Stardusten** [comment]
Should be fixed in the latest release.
