### ISSUE TITLE
Bug: Changes Made in Reading Mode are not persistent

### ISSUE THREAD

**Issue by chrisgrieser** [Stardusten/ob-table-enhancer#7]
![Kapture 2022-09-07 at 00 46 45](https://user-images.githubusercontent.com/73286100/188753598-49348a6b-1500-41e7-8459-8eb51d93952e.gif)

**Comment by Stardusten** [comment]
This issue is troublesome.

It seems that in reading mode, all methods of the editor do not change the source code. The update and save methods I wrote were executed properly, but they did not produce the expected results.

Maybe we just shouldn't make changes in reading mode.

**Comment by menagerie198** [comment]
Oddly -- I changed values in Reading Mode (and Ctrl+S)-- as noted above, they did not stick when I opened the file again. However, after reading Stardusten's response above, I switched to Edit-mode, clicked in the cell, and - boom - the previously changed but 'unsaved' values appeared! like I said: Odd. 'pooters are weird!

**Comment by menagerie198** [comment]
Is there a way of preventing the plugin from operating in Reading Mode?, or of alerting us that the edit will not stick?
I have been caught out a few times, thinking I am operating on the basis of up-to-date data, only to subsequently realise I am not. Causes operational problems (and embarrassment)

**Comment by Stardusten** [comment]
This problem should be solved in the latest version [0.3.2-alpha](https://github.com/Stardusten/ob-table-enhancer/releases/tag/0.3.2-alpha).

**Comment by menagerie198** [comment]
BRAT is telling me there is no 'main.js' file, and it cannot load 'ob-table-enhancer'

**Comment by Stardusten** [comment]
> BRAT is telling me there is no 'main.js' file, and it cannot load 'ob-table-enhancer'

This should be caused by my accidental branch switching, sorry for the trouble. I will fix this as soon as possible, until then you can download the release and install it manually.
