### ISSUE TITLE
"Create new table"失败

### ISSUE THREAD

**Issue by Junix-honor** [Stardusten/ob-table-enhancer#70]
<img width="175" alt="截屏2023-02-21 14 43 58" src="https://user-images.githubusercontent.com/61339181/220267635-9bae38b1-5d65-4ff9-a994-5e213afa1863.png">

使用右键新建表格的选项时，显示如图，无法新建表格。

**Comment by Stardusten** [comment]
看一下 Settings - Appearance - Native Menus 选项是否开启，如果开启，请关掉后再试试
