### ISSUE TITLE
无法正常显示ob双向链接的智能补全menu

### ISSUE THREAD

**Issue by Junix-honor** [Stardusten/ob-table-enhancer#72]
表格栏中输入[[时，无法正常显示ob双向链接的智能补全menu，如图所示。
<img width="230" alt="截屏2023-02-21 17 09 43" src="https://user-images.githubusercontent.com/61339181/220299835-a311ceec-2bda-4725-aabe-395a1bd4f3e7.png">
请问需要额外怎么设置吗？还是插件目前不支持呢？

**Comment by Stardusten** [comment]
目前实现编辑单元格的方式是直接将单元格设置为 contenteditable，因此 obsidian
编辑器的各种功能（比如双向链接补全等）都不能。
