### ISSUE TITLE
后台输入捕获太频繁

### ISSUE THREAD

**Issue by ku-zhen** [Stardusten/ob-table-enhancer#76]
你好，使用中发现无论一篇笔记是否有表格，是否是编辑模式，后台都在频繁的捕获键盘输入，并打印信息。有时会导致卡顿、造成不必要的资源占用。

- 建议仅在编辑模式下操作表格时，才进行相关输入的捕获
- 谢谢~

![image](https://user-images.githubusercontent.com/61906420/221848948-a045af97-1185-49a6-b13f-cb94ebcb152c.png)

**Comment by Stardusten** [comment]
是最新版本吗？如果不是，麻烦安装最新版本靠看

**Comment by ku-zhen** [comment]
感谢你的回复，上述情形发生时，ob和插件都是最新版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月1日(周三) 中午11:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Stardusten/ob-table-enhancer] 后台输入捕获太频繁 (Issue #76)




 
是最新版本吗？如果不是，麻烦安装最新版本靠看

**Comment by Stardusten** [comment]
有点奇怪，应该删掉了所有 log 再上传的。但是加一个全局的 keydown event handler 不会有什么性能问题的，这个可以放心。另外，如果不捕获事件也没法确定点击 / 按键是不是在表格里。
