### ISSUE TITLE
表格内输入时没有语法高亮

### ISSUE THREAD

**Issue by TC1024** [Stardusten/ob-table-enhancer#89]
当我添加公式时，例如：$\frac{1}{x}$，并没有出现语法高亮，导致我输入长串公式时很难判断前面是否出错

**Comment by Stardusten** [comment]
这是因为单元格里面就是一个普通的输入框，而不是 obsidian 的编辑器，因而不支持各自语法高亮，实时预览等特性。这个基本没法改。
