### ISSUE TITLE
开启该插件后会导致表格内插入的网页链接无法显示，同时导致部分templator产生的模板效果无法显示

### ISSUE THREAD

**Issue by Xieleilab** [Stardusten/ob-table-enhancer#9]
开启该插件后会导致表格内插入的网页链接无法打开，同时导致部分templator产生的模板效果无法显示

**Comment by Stardusten** [comment]
> 开启该插件后会导致表格内插入的网页链接无法打开

这个问题在 0.2.2 应该已经修好了。

> 部分templator产生的模板效果无法显示

可以提供一下无法使用的 templator 吗？不然我无法测试。

**Comment by ghost** [comment]
感谢您的开发和修复！上述问题已解决，不过在使用的过程中发现如果单元格内设置了换行（<br>）或插入了markdown格式链接,进行编辑时插入光标的操作不太顺畅，要在空白地方点好几下才能进行编辑，不知道这点能不能进一步优化

**Comment by Stardusten** [comment]
请试用一下 [0.3.1-alpha](https://github.com/Stardusten/ob-table-enhancer/releases/tag/0.3.1-alpha)，如果是表格索引导致的问题，应该能够解决。注意不要使用工作库，防止数据丢失。
